unpackaged/main/default/objects/Remote_Work_Request__c/Remote_Work_Request__c.object-meta.xml
<CustomObject>
    <label>Remote Work Request</label>
    <nameField>
        <displayFormat>RWR-{0000}</displayFormat>
        <label>Remote Work Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Remote Work Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Remote_Work_Request__c/fields/pro_Status__c.field-meta.xml
<CustomField>
    <fullName>pro_Status__c</fullName>
    <description>AB 20/07/2023 - prodigy</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Pro_CancelRemoteWorkRequest_con.cls
/*
 * Created by Prodigy Ltd on 19/10/2023.
 *
 * Description: Controller class for c-pro-cancel-remote-work-request.
 *
 * Last modified by Finbar in Prodigy on 26/10/2023.
*/
public without sharing class Pro_CancelRemoteWorkRequest_con {
    /*
    * Description: Checks if record is locked.
    *
    * Last modified by Finbar in Prodigy on 26/10/2023.
    */
    @AuraEnabled
    public static Boolean CancelRemoteWorkRequest( Id recordId ){
        Boolean result = false;

        Remote_Work_Request__c rwr = [
            SELECT 
                Id, 
                pro_Status__c
            FROM 
                Remote_Work_Request__c
            WHERE 
                Id =: recordId
            AND 
                pro_Status__c = 'Approved'
        ];

        if (rwr != null) {

            if (System.Approval.isLocked(rwr.Id)) {
                System.Approval.unlock(rwr.Id);
            }

            rwr.pro_Status__c = 'Cancelled';

            Savepoint savePoint = Database.setSavepoint();
            
            Pro_Utilities.ResultWrap updateResult = Pro_Utilities.UpdateRecords(new List<Remote_Work_Request__c>{ rwr }, savePoint);
                
            result = updateResult.Result;
        
        }

        return result;
    }
}